In [ ]:
import numpy as np



array_of_objeto = np.array([])

for i in range(3):
  array_objeto = np.array([[1],[1],[1]])
  elemento = np.append(array_of_objeto, array_objeto)
  array_of_objeto = elemento
print(array_of_objeto)

#elemento, elemento tiene que unir otra vez los 1, 1, 1.
#Como hace?

#Ahora que tenemos este fundamento sucediendo de esta forma lo que debemos 
#Generar es el componente que promueva el desarrollo de la conciencia
#La ruta que me permite formular el concepto.
#La relacion que produce unidad.


#Crea una forma en la que tu puedas unir los elmentos en un while para que
#tengas la array modificado con los datos actualizados


a = np.array([[0, 0, 0], [0, 0, 0]])

newArray = np.append(a, [[50, 60, 70]], axis = 0) 

print(newArray)

print(array_of_objeto)
a = np.arange(10)**3
print(a)
print()
print()

list_probe = list()
for i in a:
  list_probe.append(i)
  print(i)



print()
print()
print(str(len(list_probe)))
print()
print()
print(list_probe)
print()
print()
print('SEPARATOR')
print()
print()
print(array_objeto)
#array_zeros = np.zeros(array_objeto)
print(array_zeros)

b = np.linspace(0, np.pi, 3)

#Como diseñar esta cualidad.
#Es un aspecto de caracter  creativo
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 0  0  0]
 [ 0  0  0]
 [50 60 70]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0   1   8  27  64 125 216 343 512 729]


0
1
8
27
64
125
216
343
512
729


10


[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


SEPARATOR


[[1]
 [1]
 [1]]
[[[0.]]]
[0.         1.57079633 3.14159265]


In [ ]:
#Esto es puro testeo
matrix = np.array([])

